### ISSUE TITLE
Cannot find type Windows.UI.Xaml.Media.XamlLight in module Windows.winmd

### ISSUE THREAD

**Issue by ncunning** [onovotny/MSBuildSdkExtras#175]
@onovotny After Upgrading VS 2019 to 16.2 
Upgrading my Multi-targting projects to MSBuild.Sdk.Extras/2.0.31
Using NetCore 3 preview
i get an error when using the Ambient Lights from WindowsCommunityToolkit within a UWP app.

Cannot find type Windows.UI.Xaml.Media.XamlLight in module Windows.winmd

**Comment by ncunning** [comment]
Workaround:
To Solve my issue i actually had to directly reference the Windows.winmd file within my UWP Xamarin Forms App. C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.16299.0\Windows.winmd

Note: I didn't have to reference this file before in previous version of Visual Studio or MsBuildSDKExtras

**Comment by onovotny** [comment]
Do you have a small repro project?

**Comment by ncunning** [comment]
[WindowsMDTestApp.zip](https://github.com/onovotny/MSBuildSdkExtras/files/3473776/WindowsMDTestApp.zip)

**Comment by onovotny** [comment]
To be clear, you only had to reference it in the app? or the library and the app?

You also should not need to add a PackageReference to the `Microsoft.NETCore.UniversalWindowsPlatform` as the SDK brings that in in 2.x.

**Comment by ncunning** [comment]
I only had to reference in the UWP app. Not in the Library. When try to build the UWP app. I get the erro. 
Thank you for the info on Microsoft.NETCore.UniversalWindowsPlatform PackageReference. I follow the Xamarin Essentials Github repo https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Xamarin.Essentials.csproj and it still seems to have it referenced.

**Comment by onovotny** [comment]
I'm going to close this as `won't fix` since this package really only targets building class libraries. Building app projects is out of scope and you very well may need to add additional references to those.
