### ISSUE TITLE
net452 compilation failed after upgrading from 1.1.0 to 1.2.x

### ISSUE THREAD

**Issue by lextm** [onovotny/MSBuildSdkExtras#31]
https://ci.appveyor.com/project/lextm/sharpsnmplib/build/1.0.286
```
C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.4\15.0\Bin\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\projects\sharpsnmplib\SharpSnmpLib\SharpSnmpLib.csproj]
```
This error happens for both 1.2.0 and 1.2.1. Switch back to 1.1.0 and then it works again.

**Comment by poke** [comment]
I’m hitting this too with 1.2.x:

> C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.4\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by onovotny** [comment]
Strange...

Can you please use the `/bl` parameter to generate a `binlog` file (then rename it to zip) and attach it here?

**Comment by Alxandr** [comment]
Repo is available [here](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/tree/a75d85d0275df237ea9c0ba53a61d154950bb97a) (notice commit hash, master has been fixed).

**Comment by onovotny** [comment]
@lextm In your case, `dotnet test` actually rebuilds things, and that's a problem. Sdk Extras requires using `msbuild`. Can you try adding `--no-build` as a parameter to `dotnet test`? It should prevent it from rebuilding?

**Comment by onovotny** [comment]
@Alxandr same thing, you can't use `dotnet build`, it has to be `msbuild /t:build` or whatever if you use the extras. Based on your TFM's, what are you using the extras for? Looks like .NET and Net Core App?

**Comment by Alxandr** [comment]
@onovotny TBH I don't remember. Do you think I can just get rid of it?

**Comment by onovotny** [comment]
Note that msbuild now has a restore gesture.

`You can use `msbuild /restore foo.sln /t:build /p:Configuration=Release`

**Comment by onovotny** [comment]
@Alxandr: The only reason I can think of why you'd need it is to target iOS/Android/UWP or use WPF with .NET Framework. Maybe you targeted one of those at one point?

**Comment by Alxandr** [comment]
Pretty sure I didn't. I'll try removing it.

**Comment by poke** [comment]
@onovotny Not sure if my binlog is going to help you, all texts are in German. You might be better off to just clone @Alxandr’s repo, checking out `a75d85d0275d` and trying to build it yourself. I only got involved with this in an attempt to reproduce the error Alxandr was hitting on his CI; so I would expect the error to appear generally.

**Comment by onovotny** [comment]
@poke As per our comment above then, there's two issues:

1. `dotnet build` cannot build things that reference these extras; needs to be `msbuild`
2. Doesn't look like it's needed for anything anyway, so can be removed.

**Comment by poke** [comment]
I ran this with `dotnet msbuild build/build.proj /t build` (was too lazy to look up where the msbuild.exe was) and hit the same error.

Even if it can be removed, it might still be worth to figure out what the actual problem here was, or not?

**Comment by onovotny** [comment]
> I ran this with dotnet msbuild build/build.proj /t build (was too lazy to look up where the msbuild.exe was) and hit the same error.

You can't use `dotnet` at all for this. Needs to be `msbuild.exe` (and the equiv on Mono/VSfM). That's my point. If there's still an issue when you use `msbuild.exe`, I'd definitely like to fix it.

**Comment by poke** [comment]
Ah, I see. I was under the impression that `dotnet msbuild` would run the normal MSBuild anyway.

It does work with a normal MSBuild shipped with VS. Thanks!

**Comment by lextm** [comment]
@onovotny `dotnet test --no-build` does not help. For whatever reason, `dotnet test` does not locate the files generated by `msbuild`, https://ci.appveyor.com/project/lextm/sharpsnmplib/build/1.0.289 Sounds like I should report to .NET Core SDK.

**Comment by zgramana** [comment]
BTW, ran across this issue as well. Eventually tracked it down to a platform incompatibility (WPF on a Mac isn't a think). Send the PR above to put the `<Import>` for `Wpf.targets` behind an OS check condition.

**Comment by onovotny** [comment]
This should be fixed now: https://github.com/onovotny/MSBuildSdkExtras/blob/master/MSBuild.Sdk.Extras/build/platforms/NETFramework.targets#L6
